#!/bin/sh

# ir a la carpeta que contiene package.json y node_modules
cd "$(git rev-parse --show-toplevel)/Guia Turistica/backend" || exit 1

echo "Ejecutando tests..."
#npm test

# También puedes usar:
npm run test
# npm run test:ci